// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsDynamoDB
{
    [AwsDynamoDBResourceType("aws-dynamodb:index:Table")]
    public partial class Table : Pulumi.ComponentResource
    {
        [Output("outputs")]
        public Output<Pulumi.Aws.DynamoDB.Table> Outputs { get; private set; } = null!;


        /// <summary>
        /// Create a Table resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Table(string name, TableArgs args, ComponentResourceOptions? options = null)
            : base("aws-dynamodb:index:Table", name, args ?? new TableArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class TableArgs : Pulumi.ResourceArgs
    {
        [Input("advanced")]
        public Input<Inputs.IntermediateTableArgsArgs>? Advanced { get; set; }

        [Input("basic")]
        public Input<Inputs.BasicTableArgsArgs>? Basic { get; set; }

        [Input("expert")]
        public Input<Inputs.ExpertTableArgsArgs>? Expert { get; set; }

        [Input("type", required: true)]
        public Input<Pulumi.AwsDynamoDB.TableType> Type { get; set; } = null!;

        public TableArgs()
        {
        }
    }
}
