// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const TableKeyType = {
    String: "string",
    Number: "number",
} as const;

/**
 * The type of key for your DynamoDB Table.
 */
export type TableKeyType = (typeof TableKeyType)[keyof typeof TableKeyType];

export const TableType = {
    Default: "default",
    Basic: "basic",
    Advanced: "advanced",
    Expert: "expert",
} as const;

/**
 * The type of DynamoDB Table.
 */
export type TableType = (typeof TableType)[keyof typeof TableType];
