// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsDynamoDB.Inputs
{

    /// <summary>
    /// Arguments for a basic AWS DynamoDB Table.
    /// </summary>
    public sealed class BasicTableArgsArgs : Pulumi.ResourceArgs
    {
        [Input("hashKey")]
        private InputMap<string>? _hashKey;
        public InputMap<string> HashKey
        {
            get => _hashKey ?? (_hashKey = new InputMap<string>());
            set => _hashKey = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("provisioned")]
        public Input<Inputs.ProvisionedTableArgsArgs>? Provisioned { get; set; }

        [Input("rangeKey")]
        private InputMap<string>? _rangeKey;
        public InputMap<string> RangeKey
        {
            get => _rangeKey ?? (_rangeKey = new InputMap<string>());
            set => _rangeKey = value;
        }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// A map of tags assigned to the resource, including those inherited from the provider .
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        public BasicTableArgsArgs()
        {
        }
    }
}
