// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsDynamoDB.Inputs
{

    /// <summary>
    /// Arguments for a basic AWS DynamoDB Table.
    /// </summary>
    public sealed class IntermediateTableArgsArgs : Pulumi.ResourceArgs
    {
        [Input("attributes")]
        private InputList<Pulumi.Aws.DynamoDB.Inputs.TableAttributeArgs>? _attributes;

        /// <summary>
        /// List of nested attribute definitions. Only required for `hash_key` and `range_key` attributes.
        /// </summary>
        public InputList<Pulumi.Aws.DynamoDB.Inputs.TableAttributeArgs> Attributes
        {
            get => _attributes ?? (_attributes = new InputList<Pulumi.Aws.DynamoDB.Inputs.TableAttributeArgs>());
            set => _attributes = value;
        }

        [Input("globalSecondaryIndexes")]
        private InputList<Pulumi.Aws.DynamoDB.Inputs.TableGlobalSecondaryIndexArgs>? _globalSecondaryIndexes;

        /// <summary>
        /// Describe a GSI for the table;
        /// subject to the normal limits on the number of GSIs, projected
        /// attributes, etc.
        /// </summary>
        public InputList<Pulumi.Aws.DynamoDB.Inputs.TableGlobalSecondaryIndexArgs> GlobalSecondaryIndexes
        {
            get => _globalSecondaryIndexes ?? (_globalSecondaryIndexes = new InputList<Pulumi.Aws.DynamoDB.Inputs.TableGlobalSecondaryIndexArgs>());
            set => _globalSecondaryIndexes = value;
        }

        /// <summary>
        /// The name of the hash key in the index; must be
        /// defined as an attribute in the resource.
        /// </summary>
        [Input("hashKey")]
        public Input<string>? HashKey { get; set; }

        [Input("localSecondaryIndexes")]
        private InputList<Pulumi.Aws.DynamoDB.Inputs.TableLocalSecondaryIndexArgs>? _localSecondaryIndexes;

        /// <summary>
        /// Describe an LSI on the table;
        /// these can only be allocated *at creation* so you cannot change this
        /// definition after you have created the resource.
        /// </summary>
        public InputList<Pulumi.Aws.DynamoDB.Inputs.TableLocalSecondaryIndexArgs> LocalSecondaryIndexes
        {
            get => _localSecondaryIndexes ?? (_localSecondaryIndexes = new InputList<Pulumi.Aws.DynamoDB.Inputs.TableLocalSecondaryIndexArgs>());
            set => _localSecondaryIndexes = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("provisioned")]
        public Input<Inputs.ProvisionedTableArgsArgs>? Provisioned { get; set; }

        /// <summary>
        /// The name of the range key; must be defined.
        /// </summary>
        [Input("rangeKey")]
        public Input<string>? RangeKey { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// A map of tags assigned to the resource, including those inherited from the provider .
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        public IntermediateTableArgsArgs()
        {
        }
    }
}
