# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .provider import *
from .table import *
from ._inputs import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "aws-dynamodb",
  "mod": "index",
  "fqn": "pulumi_aws_dynamodb",
  "classes": {
   "aws-dynamodb:index:Table": "Table"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "aws-dynamodb",
  "token": "pulumi:providers:aws-dynamodb",
  "fqn": "pulumi_aws_dynamodb",
  "class": "Provider"
 }
]
"""
)
